[package]
name = "handler"
version = "0.1.0"
edition = "2024"

[dependencies]
entity = {path = "../entity"}
axum = { version = "0.8.4", features = ["default", "macros"]}
serde = { version = "1.0.219", features = ["derive"]}
sea-orm = {version = "1.1.11", features = ["sqlx-postgres", "runtime-tokio", "macros", "debug-print"]}
utoipa = {version = ">=5.3.1", features = ["axum_extras", "decimal", "chrono"]}
utoipa-axum = "0.2.0"
rust_decimal = { version = "1.37.1", features = ["serde", "serde_json"] }
anyhow = "1.0.98"
log = "0.4.27"
tracing = "0.1.41"