[package]
name = "handler"
version = "0.1.0"
edition = "2024"

[dependencies]
entity = {path = "../entity"}
axum = { version = "0.8.4", features = ["default"]}
serde = { version = "1.0.219", features = ["derive"]}
sea-orm = {version = "1.1.11", features = ["sqlx-postgres", "runtime-tokio", "macros"]}
anyhow = "1.0.98"